import type { Enemy } from "../types/Enemy";

export const enemies: Enemy[] = [
  {
    x: 200,
    y: 200,
    radius: 15,
    vx: 2,
    vy: 1,
    speed: 4,
    color: "yellow",
    firingPattern: {
      bulletCount: 3,
      initialAngle: 90,
      fireRate: 2,
      lastFired: 0,
      speed: 4,
    },
    hp: 2,
  },
  {
    x: 1000,
    y: 300,
    radius: 15,
    vx: -1,
    vy: 2,
    speed: 2,
    color: "blue",
    firingPattern: {
      bulletCount: 5,
      initialAngle: 0,
      fireRate: 0.8,
      lastFired: 0,
      speed: 3,
    },
    hp: 3,
  },
  {
    x: 400,
    y: 900,
    radius: 15,
    vx: 1,
    vy: -2,
    speed: 3,
    color: "pink",
    firingPattern: {
      bulletCount: 1,
      initialAngle: 45,
      fireRate: 2,
      lastFired: 0,
      speed: 3,
    },
    hp: 2,
  },
];
